### ISSUE TITLE
Не заполняется код метаданных (закомментирована строка)

### ISSUE THREAD

**Issue by milanse** [alekseybochkov/EventLogLoader#1]
Можно попробовать заменить на
OneEvent.MetadataID = rs("metadataCodes").Split(New Char() {","c})[0]

https://github.com/alekseybochkov/EventLogLoader/blob/b957dc06026a6f3534a057a852efe3e8070ba6fd/EventLogLoaderService/Service1.vb#L1229

**Comment by alex-bochkov** [comment]
Поправил. Хотя у себя в ЖР не нашел ни одного случая, когда в колонке metadataCodes было бы несколько значений через запятую.
