### ISSUE TITLE
динамические индексы elasticsearch

### ISSUE THREAD

**Issue by farukshin** [alekseybochkov/EventLogLoader#14]
есть ли возможность выгружить логи журнала регистрации в индексы в зависимости от даты записи ЖР? Можно задать лишь наименование индекса, например buh1c
Хотелось бы иметь возможность:
для записей ЖР апреля 2017 г. выгрузить в индекс buh1c-2017-04 
для записей ЖР мая 2017 г. выгрузить в индекс buh1c-2017-05
Необходимо для гибкого администрирования логов в ElasticSearch

**Comment by alex-bochkov** [comment]
@farukshin добавил возможность динамического формирования имени индекса на основе даты. 
В UI вынесено поле для указания маски даты.

**Comment by farukshin** [comment]
Алексей, когда планируется сборка релиза?
