### ISSUE TITLE
Смещение даты (DataTime) на 4 часа вперед в elasticsearch

### ISSUE THREAD

**Issue by SemyonAT** [alekseybochkov/EventLogLoader#18]
Использую версию 2.2-beta.
Когда выгружаю данные в MS SQL время корректное, но, когда данные выгружаю в elasticsearch данные записываются на 4 часа вперед, временные зоны везде одинаковые. Подскажите может я что-то неправильно делаю?

**Comment by dmpas** [comment]
@SemyonAT есть такой косяк при выгрузке в эластик. Я исправлял его у себя.

https://github.com/alekseybochkov/EventLogLoader/pull/16/commits/b1b4df428f66b5c2b0041b6c9782522121fd4217

**Comment by SemyonAT** [comment]
Спасибо! Подскажи как правильно пересобрать проект.

**Comment by dmpas** [comment]
@SemyonAT получилось? у меня просто всё руки не доходят.
