### ISSUE TITLE
Выгрузка в Elasticsearch

### ISSUE THREAD

**Issue by JohnyDeath** [alekseybochkov/EventLogLoader#2]
Хотелось бы иметь возможность в качестве приемника указывать logstash
https://www.elastic.co/products/logstash

**Comment by alex-bochkov** [comment]
@JohnyDeath - добавил выгрузку в ES. Если есть желание протестировать - сборка тут https://github.com/alekseybochkov/EventLogLoader/releases/tag/2.0-beta

**Comment by JohnyDeath** [comment]
@alekseybochkov спасибо, поэкспериментирую.
Там проблемы с многострочными комментариями, о которых писали на инфостарте, остались?

**Comment by JohnyDeath** [comment]
Работает. Спасибо!
