### ISSUE TITLE
Добавить лицензию

### ISSUE THREAD

**Issue by YPermitin** [alekseybochkov/EventLogLoader#5]
Необходимо добавить лицензию, чтобы понимать о возможностях использования для своих целей.

**Comment by dmpas** [comment]
![screen](https://cloud.githubusercontent.com/assets/5665433/21804641/19544cae-d741-11e6-8d1d-f2377ab9c6dd.png)

Судя по всему, GPL.

**Comment by YPermitin** [comment]
@dmpas далеко запрятано =)

По "фэн-шую" правильней бы сюда добавить эту лицензию.

**Comment by alex-bochkov** [comment]
@YPermitin - я добавил стандартную лицензию GNU GPL.

**Comment by YPermitin** [comment]
@alekseybochkov Отлично! Спасибо!
