### ISSUE TITLE
Возможность задавать имена полей для ES

### ISSUE THREAD

**Issue by JohnyDeath** [alekseybochkov/EventLogLoader#9]
Хотелось бы иметь возможность задавать имена полей для ES, чтобы смотреть в Kibana на человеческие русские имена. Или хотя бы жестко задать их в коде программы.

**Comment by alex-bochkov** [comment]
@JohnyDeath - добавил возможность указания синонимов для полей. Пересохраните конфиг через UI и новые свойства там появятся. 
Если **ESUseSynonymsForFieldsNames** = **true**, то будут использоваться заданные имена полей из конфига.

**Comment by JohnyDeath** [comment]
В соседней задаче описал проблемы с версией 2.2 https://github.com/alekseybochkov/EventLogLoader/issues/10#issuecomment-281260919
